sudo: required
language: java
jdk:
- oraclejdk8
- oraclejdk10
services:
- docker
before_deploy:
- echo "DOCKER_PASSWORD"
- echo "$DOCKER_PASSWORD"
- echo "DOCKER_USERNAME"
- echo "$DOCKER_USERNAME"
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  skip_cleanup: true
  provider: script
  script:
  - docker tag se.kth.id1212/appserv-spring:1.0 sekthid1212/appserv-spring-dev:1.0
  - docker push sekthid1212/appserv-spring-dev:1.0
  on:
    branch: develop
after_script:
- docker images
- echo "Current directory is $(pwd)"
- ls
- cat target/site/pmd/cpd.xml
- cat target/site/pmd/pmd.xml
- cat target/site/findbugs/findbugsXml.xml
env:
  global:
    - secure: dFWG0m52B2yW3S+xT+aycOsHfi7FqJV511YczG2AwTPXPOhQTDtTuWZq0or2+Z7t26e8bbdeD1WdDgm5UYlOefCGc7SM3HEqB0hvtWt+m8PosqFQazhfHzw5LEUnyB1DPhIposkRKW6ZhrZajiK9uMaOdUskTY7HvYIpXNYUSTunrcnFbTuOFNdMVm4jrzfAKuswca/EzxmuOfkQusZpZNGt6DqPs1E9sBxHjirzZVgh4TddvK8qDJwo3YxcGWZb13Pa33pdqQAca+gKFeyndDIsjYvB32ewPfVP+Hz0SlGwQ8goMfxurFQZmuy2Ik2d40js++6fAXTqO80U5Y2VOYBVKm7/P7fES5ElxqHlIxJXNVmAG1U/G7wMx9mm8aEcdz31+aR0YNr+sUdqTftuHwWzRWaGcsrh1jbc18/l+L+iEOyrGp9NCiO+NwBdouDwqiI6NWWi7ct+5DLqmK7JyyTUgES6d9paM8hU/5Pls7mPNelI7cIY3k3NJsxLsjUlZfFiqtLKaifjIb9bbMTm9ZmoCY990JCV8NpxPp71HJruwvMj8caYqv/uUdYgctgwf4sGK++3hGzEx8oe1YksCXScvObe8rrI3Fl8PKc22YwkGQLTo03hDT1rj2q8v1Lm/kaLSD3cP/a2sV421VveHO/M76fKQG6UsS7lm2s2W/4=
    - secure: X0y03awt9gX6hXakWavza7VcZA53lDEjWeWYIX/p9O+L+3u9zecWN7ixVccKgVRALI6JBDJyA9N4bUARh+1EAJOe7Egns3HQJn8tFB/DtXQ9Hs3R0B1xfHn2LUI3PnmEDyN4873DAs7YHefaW/tzaQ3iUGNyf9CSE+LmWHWiXVMD8SP/eNtphJjpJYHsR2hYu5DWv+BQeVQYS16kNwTqcP+BIvqEvXWUwWDiN9+r+8xk00zHhEDk1KpZ9jfPNrCzRDuv41v9LYb3fqsnOFCbomG43KfIoZQpBOZQ4xRDq3HUCSAxqZRU0yqFOJKIeB6ieVgvtqudjSqKiDDOrP4ycrhenmLEgxZEbI91dDNJBDVnSNFcQ4vD3IkxcfzcA1vS6ly3z6lrYGNXIsnZsEcDy9c8fRp2Fwd7uFoO1uT2/20VB3fuHDF3olL4uPpbyT82pfYN6yB7fugotiGCNZewuHmDYdTuypjrs2dpEroXSgxckYYcRDCgAHxngSLCevoAW9f6KxDhI68jE5nM4YJG30ppSKcBPCD9MuvS6dpw/cRcBopQ8gYoc0PAybNzQO2838zy0HPJU1NxL8WdwwPQTB5yolECLzvGGg/CU+ILunkjE9miwBvkK1grYESTXiiBP+ppsDhAR4VS+uVY3wLGPPlO0oWnbGQWJqCF5ScR91w=
